name: Build and Deploy the app
run-name: ${{ github.actor }}
on: 
  push:
    branches:
      - main
      - dev
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: actions/setup-node@v3
        with:
          node-version: 18.12.1
      - run: npm ci
      - if: github.ref == 'refs/heads/main'
        run: npm run build -- --configuration=production
      - if: github.ref != 'refs/heads/main'
        run: npm run build -- --configuration=development
  publish:
    needs: [build]
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: docker/login-action@v2
        with: 
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PAT }}
      - if: github.ref == 'refs/heads/main'
        uses: docker/build-push-action@v3
        with:
          push: true
          build-args: 'ANGULAR_ENV=production'
          tags: ${{ secrets.DOCKER_USER }}/yaeb-front:latest
      - if: github.ref != 'refs/heads/main'
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ${{ secrets.DOCKER_USER }}/yaeb-front:dev